name: flutter_log_overlay
description: A global pop-up widget for displaying logs, which can be displayed or hidden. The global display refreshes the content asynchronously.
version: 0.0.7
homepage: https://github.com/wl1395182472/flutter_log_overlay

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: null
